#!/usr/bin/env bash
# A script that loops through 1 to 10 using while loop
# displays "bad luck" on the 4th loop iteration
# displays "good luck" on the 8th loop iteration

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
